### ISSUE TITLE
update for async I/O?

### ISSUE THREAD

**Issue by hools** [BobDickinson/corona-s3#1]
Just found your module and got it running in a jiffy. It's awesome!
My question: when you wrote it, 2 yrs ago, corona async support wasn't there...has their SDK advanced enough to warrant updating the request logic?

Thanks!

ps: also curious if this code ever saw production usage and how did it do? seems solid at first glance...

**Comment by BobDickinson** [comment]
The S3 code never saw production, though I did use it pretty extensively in
my development before I bailed.  My final concern ended up being the
complexity of managing access (not being comfortable distributing the app
key built-in to the app and not being totally happy with how complex the
other solutions were - namely distributing pre-signed access tokens).

I was actually the person who re-wrote the Corona networking support (what
they called "Networking 2.0") and I think it obsoletes the async approach
in the S3 project.  I specifically made sure that the stuff I was annoyed
with (lack of access to details of the protocol, the ability to cancel an
async request, etc) got addressed in the new Corona networking code.

If you do want to use S3 from Corona my suggestion would be to use the new
built-in networking APIs, and of course feel free to port s3.lua if it's
useful.

Sorry I can't be of more help.  I haven't looked at any of this stuff in
quite a while and haven't been doing any Corona/Lua development for over a
year.

Bob
